package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	resetMarker       = "generate:reset"
	generatedFileName = "reset.gen.go"
	zeroFuncName      = "resetGenZero"
)

type packageInfo struct {
	dir     string
	name    string
	structs []structInfo
}

type structInfo struct {
	name       string
	typeParams []string
	fields     []*ast.Field
}

type generator struct {
	counter int
}

type generatedSourceData struct {
	PackageName  string
	ZeroFuncName string
	Methods      []resetMethodData
}

type resetMethodData struct {
	ReceiverType string
	Statements   []resetStatement
}

type resetStatement struct {
	Slice        *sliceResetStatement
	Clear        *clearStatement
	ForRange     *forRangeStatement
	IfNotNil     *ifNotNilStatement
	PointerValue *pointerValueResetStatement
	Interface    *interfaceResetStatement
	Named        *namedResetStatement
}

type sliceResetStatement struct {
	Access string
}

type clearStatement struct {
	Access string
}

type forRangeStatement struct {
	Index  string
	Access string
	Body   []resetStatement
}

type ifNotNilStatement struct {
	Access string
	Body   []resetStatement
}

type pointerValueResetStatement struct {
	Resetter     string
	Access       string
	ZeroFuncName string
}

type interfaceResetStatement struct {
	Resetter string
	Access   string
}

type namedResetStatement struct {
	Resetter     string
	Access       string
	ZeroFuncName string
}

const generatedSourceTemplate = `// Code generated by go run ./cmd/reset; DO NOT EDIT.

package {{ .PackageName }}

func {{ .ZeroFuncName }}[T any](v *T) {
	var zero T
	*v = zero
}
{{ range .Methods }}
func (v *{{ .ReceiverType }}) Reset() {
	if v == nil {
		return
	}
{{ template "resetStatements" .Statements }}
}
{{ end }}
{{ define "resetStatements" }}
{{ range . }}
{{ with .Slice }}{{ .Access }} = {{ .Access }}[:0]
{{ end }}
{{ with .Clear }}clear({{ .Access }})
{{ end }}
{{ with .ForRange }}for {{ .Index }} := range {{ .Access }} {
{{ template "resetStatements" .Body }}
}
{{ end }}
{{ with .IfNotNil }}if {{ .Access }} != nil {
{{ template "resetStatements" .Body }}
}
{{ end }}
{{ with .PointerValue }}if {{ .Resetter }}, ok := any({{ .Access }}).(interface{ Reset() }); ok {
{{ .Resetter }}.Reset()
} else {
{{ .ZeroFuncName }}({{ .Access }})
}
{{ end }}
{{ with .Interface }}if {{ .Resetter }}, ok := {{ .Access }}.(interface{ Reset() }); ok {
{{ .Resetter }}.Reset()
} else {
{{ .Access }} = nil
}
{{ end }}
{{ with .Named }}if {{ .Resetter }}, ok := any(&{{ .Access }}).(interface{ Reset() }); ok {
{{ .Resetter }}.Reset()
} else {
{{ .ZeroFuncName }}(&{{ .Access }})
}
{{ end }}
{{ end }}
{{ end }}`

var generatedSourceTmpl = template.Must(template.New("generated source").Parse(generatedSourceTemplate))

func main() {
	flag.Parse()

	root := "."
	if flag.NArg() > 0 {
		root = flag.Arg(0)
	}

	packages, err := scanPackages(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan packages: %v\n", err)
		os.Exit(1)
	}

	for _, pkg := range packages {
		if err := generatePackage(pkg); err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", pkg.dir, err)
			os.Exit(1)
		}
	}
}

func scanPackages(root string) ([]packageInfo, error) {
	var packages []packageInfo

	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() {
			return nil
		}
		if shouldSkipDir(path, entry.Name()) {
			return filepath.SkipDir
		}

		pkg, err := parsePackage(path)
		if err != nil {
			return err
		}
		if len(pkg.structs) > 0 {
			packages = append(packages, pkg)
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	return packages, nil
}

func shouldSkipDir(path, name string) bool {
	if path == "." {
		return false
	}

	switch name {
	case ".git", ".gocache", ".gomodcache", "vendor":
		return true
	default:
		return strings.HasPrefix(name, ".")
	}
}

func parsePackage(dir string) (packageInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return packageInfo{}, err
	}

	fset := token.NewFileSet()
	var pkg packageInfo

	for _, entry := range entries {
		if entry.IsDir() || !isSourceFile(entry.Name()) {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
		if err != nil {
			return packageInfo{}, err
		}

		if pkg.name == "" {
			pkg.dir = dir
			pkg.name = file.Name.Name
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || (!hasResetMarker(genDecl.Doc) && !hasResetMarker(typeSpec.Doc)) {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				pkg.structs = append(pkg.structs, structInfo{
					name:       typeSpec.Name.Name,
					typeParams: typeParamNames(typeSpec.TypeParams),
					fields:     structType.Fields.List,
				})
			}
		}
	}

	return pkg, nil
}

func isSourceFile(name string) bool {
	return strings.HasSuffix(name, ".go") &&
		!strings.HasSuffix(name, "_test.go") &&
		name != generatedFileName
}

func hasResetMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}

	for _, comment := range group.List {
		if strings.Contains(comment.Text, resetMarker) {
			return true
		}
	}

	return false
}

func typeParamNames(params *ast.FieldList) []string {
	if params == nil {
		return nil
	}

	names := make([]string, 0, len(params.List))
	for _, field := range params.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}

	return names
}

func generatePackage(pkg packageInfo) error {
	var buf bytes.Buffer
	data := generatedSourceData{
		PackageName:  pkg.name,
		ZeroFuncName: zeroFuncName,
		Methods:      make([]resetMethodData, 0, len(pkg.structs)),
	}
	g := generator{}

	for _, strct := range pkg.structs {
		data.Methods = append(data.Methods, g.generateResetMethod(strct))
	}

	if err := generatedSourceTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute generated source template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w\n%s", err, buf.String())
	}

	return os.WriteFile(filepath.Join(pkg.dir, generatedFileName), formatted, 0o644)
}

func (g *generator) generateResetMethod(strct structInfo) resetMethodData {
	receiverType := strct.name
	if len(strct.typeParams) > 0 {
		receiverType += "[" + strings.Join(strct.typeParams, ", ") + "]"
	}

	return resetMethodData{
		ReceiverType: receiverType,
		Statements:   g.generateFields("v", strct.fields),
	}
}

func (g *generator) generateFields(base string, fields []*ast.Field) []resetStatement {
	var statements []resetStatement
	for _, field := range fields {
		names := fieldNames(field)
		for _, name := range names {
			statements = append(statements, g.generateReset(base+"."+name, field.Type)...)
		}
	}

	return statements
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, name := range field.Names {
			if name.Name != "_" {
				names = append(names, name.Name)
			}
		}
		return names
	}

	name := embeddedFieldName(field.Type)
	if name == "" {
		return nil
	}

	return []string{name}
}

func embeddedFieldName(expr ast.Expr) string {
	switch typ := expr.(type) {
	case *ast.Ident:
		return typ.Name
	case *ast.SelectorExpr:
		return typ.Sel.Name
	case *ast.StarExpr:
		return embeddedFieldName(typ.X)
	default:
		return ""
	}
}

func (g *generator) generateReset(access string, typ ast.Expr) []resetStatement {
	switch expr := typ.(type) {
	case *ast.ArrayType:
		if expr.Len == nil {
			return []resetStatement{{Slice: &sliceResetStatement{Access: access}}}
		}

		index := g.nextName("i")
		return []resetStatement{
			{
				ForRange: &forRangeStatement{
					Index:  index,
					Access: access,
					Body:   g.generateReset(access+"["+index+"]", expr.Elt),
				},
			},
		}
	case *ast.MapType:
		return []resetStatement{{Clear: &clearStatement{Access: access}}}
	case *ast.StarExpr:
		return g.generatePointerReset(access, expr.X)
	case *ast.StructType:
		return g.generateFields(access, expr.Fields.List)
	case *ast.InterfaceType:
		return g.generateInterfaceReset(access)
	default:
		return g.generateNamedReset(access)
	}
}

func (g *generator) generatePointerReset(access string, elem ast.Expr) []resetStatement {
	var body []resetStatement
	switch expr := elem.(type) {
	case *ast.ArrayType, *ast.MapType, *ast.StarExpr, *ast.StructType, *ast.InterfaceType:
		body = g.generateReset("(*"+access+")", expr)
	default:
		resetter := g.nextName("resetter")
		body = []resetStatement{
			{
				PointerValue: &pointerValueResetStatement{
					Resetter:     resetter,
					Access:       access,
					ZeroFuncName: zeroFuncName,
				},
			},
		}
	}

	return []resetStatement{
		{
			IfNotNil: &ifNotNilStatement{
				Access: access,
				Body:   body,
			},
		},
	}
}

func (g *generator) generateInterfaceReset(access string) []resetStatement {
	resetter := g.nextName("resetter")

	return []resetStatement{
		{
			IfNotNil: &ifNotNilStatement{
				Access: access,
				Body: []resetStatement{
					{
						Interface: &interfaceResetStatement{
							Resetter: resetter,
							Access:   access,
						},
					},
				},
			},
		},
	}
}

func (g *generator) generateNamedReset(access string) []resetStatement {
	resetter := g.nextName("resetter")

	return []resetStatement{
		{
			Named: &namedResetStatement{
				Resetter:     resetter,
				Access:       access,
				ZeroFuncName: zeroFuncName,
			},
		},
	}
}

func (g *generator) nextName(prefix string) string {
	g.counter++
	return fmt.Sprintf("%s%d", prefix, g.counter)
}
