package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const (
	resetMarker       = "generate:reset"
	generatedFileName = "reset.gen.go"
	zeroFuncName      = "resetGenZero"
)

type packageInfo struct {
	dir     string
	name    string
	structs []structInfo
}

type structInfo struct {
	name       string
	typeParams []string
	fields     []*ast.Field
}

type generator struct {
	buf     *bytes.Buffer
	counter int
}

func main() {
	flag.Parse()

	root := "."
	if flag.NArg() > 0 {
		root = flag.Arg(0)
	}

	packages, err := scanPackages(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan packages: %v\n", err)
		os.Exit(1)
	}

	for _, pkg := range packages {
		if err := generatePackage(pkg); err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", pkg.dir, err)
			os.Exit(1)
		}
	}
}

func scanPackages(root string) ([]packageInfo, error) {
	var packages []packageInfo

	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() {
			return nil
		}
		if shouldSkipDir(path, entry.Name()) {
			return filepath.SkipDir
		}

		pkg, err := parsePackage(path)
		if err != nil {
			return err
		}
		if len(pkg.structs) > 0 {
			packages = append(packages, pkg)
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	return packages, nil
}

func shouldSkipDir(path, name string) bool {
	if path == "." {
		return false
	}

	switch name {
	case ".git", ".gocache", ".gomodcache", "vendor":
		return true
	default:
		return strings.HasPrefix(name, ".")
	}
}

func parsePackage(dir string) (packageInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return packageInfo{}, err
	}

	fset := token.NewFileSet()
	var pkg packageInfo

	for _, entry := range entries {
		if entry.IsDir() || !isSourceFile(entry.Name()) {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
		if err != nil {
			return packageInfo{}, err
		}

		if pkg.name == "" {
			pkg.dir = dir
			pkg.name = file.Name.Name
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || (!hasResetMarker(genDecl.Doc) && !hasResetMarker(typeSpec.Doc)) {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				pkg.structs = append(pkg.structs, structInfo{
					name:       typeSpec.Name.Name,
					typeParams: typeParamNames(typeSpec.TypeParams),
					fields:     structType.Fields.List,
				})
			}
		}
	}

	return pkg, nil
}

func isSourceFile(name string) bool {
	return strings.HasSuffix(name, ".go") &&
		!strings.HasSuffix(name, "_test.go") &&
		name != generatedFileName
}

func hasResetMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}

	for _, comment := range group.List {
		if strings.Contains(comment.Text, resetMarker) {
			return true
		}
	}

	return false
}

func typeParamNames(params *ast.FieldList) []string {
	if params == nil {
		return nil
	}

	names := make([]string, 0, len(params.List))
	for _, field := range params.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}

	return names
}

func generatePackage(pkg packageInfo) error {
	var buf bytes.Buffer
	g := generator{buf: &buf}

	fmt.Fprintln(&buf, "// Code generated by go run ./cmd/reset; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", pkg.name)
	fmt.Fprintf(&buf, "func %s[T any](v *T) {\n", zeroFuncName)
	fmt.Fprintln(&buf, "\tvar zero T")
	fmt.Fprintln(&buf, "\t*v = zero")
	fmt.Fprintln(&buf, "}")

	for _, strct := range pkg.structs {
		g.generateResetMethod(strct)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w\n%s", err, buf.String())
	}

	return os.WriteFile(filepath.Join(pkg.dir, generatedFileName), formatted, 0o644)
}

func (g *generator) generateResetMethod(strct structInfo) {
	receiverType := strct.name
	if len(strct.typeParams) > 0 {
		receiverType += "[" + strings.Join(strct.typeParams, ", ") + "]"
	}

	fmt.Fprintln(g.buf)
	fmt.Fprintf(g.buf, "func (v *%s) Reset() {\n", receiverType)
	fmt.Fprintln(g.buf, "\tif v == nil {")
	fmt.Fprintln(g.buf, "\t\treturn")
	fmt.Fprintln(g.buf, "\t}")

	g.generateFields("v", strct.fields, "\t")

	fmt.Fprintln(g.buf, "}")
}

func (g *generator) generateFields(base string, fields []*ast.Field, indent string) {
	for _, field := range fields {
		names := fieldNames(field)
		for _, name := range names {
			g.generateReset(base+"."+name, field.Type, indent)
		}
	}
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, name := range field.Names {
			if name.Name != "_" {
				names = append(names, name.Name)
			}
		}
		return names
	}

	name := embeddedFieldName(field.Type)
	if name == "" {
		return nil
	}

	return []string{name}
}

func embeddedFieldName(expr ast.Expr) string {
	switch typ := expr.(type) {
	case *ast.Ident:
		return typ.Name
	case *ast.SelectorExpr:
		return typ.Sel.Name
	case *ast.StarExpr:
		return embeddedFieldName(typ.X)
	default:
		return ""
	}
}

func (g *generator) generateReset(access string, typ ast.Expr, indent string) {
	switch expr := typ.(type) {
	case *ast.ArrayType:
		if expr.Len == nil {
			fmt.Fprintf(g.buf, "%s%s = %s[:0]\n", indent, access, access)
			return
		}

		index := g.nextName("i")
		fmt.Fprintf(g.buf, "%sfor %s := range %s {\n", indent, index, access)
		g.generateReset(access+"["+index+"]", expr.Elt, indent+"\t")
		fmt.Fprintf(g.buf, "%s}\n", indent)
	case *ast.MapType:
		fmt.Fprintf(g.buf, "%sclear(%s)\n", indent, access)
	case *ast.StarExpr:
		g.generatePointerReset(access, expr.X, indent)
	case *ast.StructType:
		g.generateFields(access, expr.Fields.List, indent)
	case *ast.InterfaceType:
		g.generateInterfaceReset(access, indent)
	default:
		g.generateNamedReset(access, indent)
	}
}

func (g *generator) generatePointerReset(access string, elem ast.Expr, indent string) {
	fmt.Fprintf(g.buf, "%sif %s != nil {\n", indent, access)

	switch expr := elem.(type) {
	case *ast.ArrayType, *ast.MapType, *ast.StarExpr, *ast.StructType, *ast.InterfaceType:
		g.generateReset("(*"+access+")", expr, indent+"\t")
	default:
		resetter := g.nextName("resetter")
		fmt.Fprintf(g.buf, "%s\tif %s, ok := any(%s).(interface{ Reset() }); ok {\n", indent, resetter, access)
		fmt.Fprintf(g.buf, "%s\t\t%s.Reset()\n", indent, resetter)
		fmt.Fprintf(g.buf, "%s\t} else {\n", indent)
		fmt.Fprintf(g.buf, "%s\t\t%s(%s)\n", indent, zeroFuncName, access)
		fmt.Fprintf(g.buf, "%s\t}\n", indent)
	}

	fmt.Fprintf(g.buf, "%s}\n", indent)
}

func (g *generator) generateInterfaceReset(access, indent string) {
	resetter := g.nextName("resetter")
	fmt.Fprintf(g.buf, "%sif %s != nil {\n", indent, access)
	fmt.Fprintf(g.buf, "%s\tif %s, ok := %s.(interface{ Reset() }); ok {\n", indent, resetter, access)
	fmt.Fprintf(g.buf, "%s\t\t%s.Reset()\n", indent, resetter)
	fmt.Fprintf(g.buf, "%s\t} else {\n", indent)
	fmt.Fprintf(g.buf, "%s\t\t%s = nil\n", indent, access)
	fmt.Fprintf(g.buf, "%s\t}\n", indent)
	fmt.Fprintf(g.buf, "%s}\n", indent)
}

func (g *generator) generateNamedReset(access, indent string) {
	resetter := g.nextName("resetter")
	fmt.Fprintf(g.buf, "%sif %s, ok := any(&%s).(interface{ Reset() }); ok {\n", indent, resetter, access)
	fmt.Fprintf(g.buf, "%s\t%s.Reset()\n", indent, resetter)
	fmt.Fprintf(g.buf, "%s} else {\n", indent)
	fmt.Fprintf(g.buf, "%s\t%s(&%s)\n", indent, zeroFuncName, access)
	fmt.Fprintf(g.buf, "%s}\n", indent)
}

func (g *generator) nextName(prefix string) string {
	g.counter++
	return fmt.Sprintf("%s%d", prefix, g.counter)
}
